server:
  port: 8085   # single place only

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: <your-client-secret>
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/mycompany-realm/protocol/openid-connect/token

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/products/**
          filters:
            - RemoveRequestHeader=Cookie
